
# \u5F00\u53D1\u73AF\u5883\u914D\u7F6E
server:
  # \u670D\u52A1\u5668\u7684HTTP\u7AEF\u53E3\uFF0C\u9ED8\u8BA4\u4E3A8080
  port: 8085
  servlet:
    # \u5E94\u7528\u7684\u8BBF\u95EE\u8DEF\u5F84
    context-path: /
  tomcat:
    # tomcat\u7684URI\u7F16\u7801
    uri-encoding: UTF-8
    # \u8FDE\u63A5\u6570\u6EE1\u540E\u7684\u6392\u961F\u6570\uFF0C\u9ED8\u8BA4\u4E3A100
    accept-count: 1000
    threads:
      # tomcat\u6700\u5927\u7EBF\u7A0B\u6570\uFF0C\u9ED8\u8BA4\u4E3A200
      max: 800
      # Tomcat\u542F\u52A8\u521D\u59CB\u5316\u7684\u7EBF\u7A0B\u6570\uFF0C\u9ED8\u8BA4\u503C10
      min-spare: 100

# \u65E5\u5FD7\u914D\u7F6E
logging:
  level:
    com.hotel: debug
    org.springframework: warn

# Spring\u914D\u7F6E
spring:
  # \u6587\u4EF6\u4E0A\u4F20
  servlet:
    multipart:
      # \u5355\u4E2A\u6587\u4EF6\u5927\u5C0F
      max-file-size: 10MB
      # \u8BBE\u7F6E\u603B\u4E0A\u4F20\u7684\u6587\u4EF6\u5927\u5C0F
      max-request-size: 20MB
  # \u670D\u52A1\u6A21\u5757
  devtools:
    restart:
      # \u70ED\u90E8\u7F72\u5F00\u5173
      enabled: true
  # redis \u914D\u7F6E
  redis:
    # \u5730\u5740
    host: 192.168.91.50
    # \u7AEF\u53E3\uFF0C\u9ED8\u8BA4\u4E3A6379
    port: 6379
    # \u6570\u636E\u5E93\u7D22\u5F15
    database: 5
    # \u5BC6\u7801
    password:
    # \u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4
    timeout: 10s
    lettuce:
      pool:
        # \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5
        min-idle: 0
        # \u8FDE\u63A5\u6C60\u4E2D\u7684\u6700\u5927\u7A7A\u95F2\u8FDE\u63A5
        max-idle: 8
        # \u8FDE\u63A5\u6C60\u7684\u6700\u5927\u6570\u636E\u5E93\u8FDE\u63A5\u6570
        max-active: 8
        # #\u8FDE\u63A5\u6C60\u6700\u5927\u963B\u585E\u7B49\u5F85\u65F6\u95F4\uFF08\u4F7F\u7528\u8D1F\u503C\u8868\u793A\u6CA1\u6709\u9650\u5236\uFF09
        max-wait: -1ms
# https://open.alipay.com/develop/sandbox/account \u652F\u4ED8\u5B9D\u5F00\u653E\u5E73\u53F0
alipay:
  # \u5E94\u7528APPID
  appid : 902000135623824
  # \u5546\u6237\u79C1\u94A5\uFF0C\u60A8\u7684PKCS8\u683C\u5F0FRSA2\u79C1\u94A5 \u5E94\u7528\u79C1\u94A5
  privatekey : MIIvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDWHYGDKo1bB5kxDyIC3k7FyzfZGoJoKxRhpA/nMrm61d1/2EAqNJYIRl9Gcai7bL5MtHCXockYKX0AWGoSjEnl0tVaZjd6GRNjzcVymw664h6XzccjxE6c7ONeU0jFngEZeQ9vGrqyo2tz5wjqFoekS2zIinhHKX/2ULBGWhA3SEXiyTNI3KyYkcpL1ylKEy8N6O+JnQ7cqYR5OpIcBTnhuEImBxzL02AT1mgzCNr5paWgM4x8kD0r3KoulCEWp9Ab5CpDZlthgFYG3VjNSARKmx5BT9UcZD8gXSpIU3ozd9PeilgvbtgeMaiXkT9w/4bTsKCLOCUkNmHl89D5UWhfAgMBAAECggEBAKzJXNWTxkTaieZMNv8nlVwK1cPOn8QeV7E/61GA3t8GbVwZEBa/HwAIgiRf3nF5nMxbpKzI83YbLPPVZawYKB5eGKx95nESwVH+IUOOG8H2bgfFGNolNedvR0C8ZvKKwopi5nCbmmREepcqr0fw7H9KGrxu+gc7VzdYABiV35Yrs7ywk8AMMxxuInmTX63QIrPlyyKZqs65YPpunbOFXsj0BN9CgOg5M3cFwCaRUYMS8R7QoQN2EM3Kwq75o760JyGej8T9SZxowYOnPPSb7e8tzbRt1i7F91jkq7toWWZB0QIQn/3dIGjEra7ekjK7trIGaVmnNsII7SC3LcT2ImkCgYEA7zq0aCWmvDrQ6kSN8wNa4kB3+26ugvL0IaiNW+aK0OuVX+qGouOX9L/xb8qRS0fTcjdiyJhI82iDowxFq0hp0DqwON1WnJekJrJwXPFvlx0LobUofePQHmP52mRDUJ7nWG8XrTlPF3H4CrMbet43eoa7L0JjfPeM/YqvZrIFJ/0CgYEA5SAYZIj7jolXTJo8Ibj4qqZvGrOWgWDJ+9qE8qADOH3sVP/iY6Ml2LtYQEYIwvzSlRAjec6qS2yPPn3JI69K3wm28JUytwzNdKEetHs6utB6kP9cKYdLVLRLZZ1cvX5hGN5etcrIEz4fVx3fQH0qBdDLWjvSTqra9AUL7wnZGosCgYBT7mO3GmaaKYR8fJrUxLuRH484zoc5eCXA3VLjCEpxrAWXRkAATBtXCjSZxRces09zBg2JVSxbAbMVdEvJITnGjaCgAr/NZsJ3tSkI4sgE23LmRBm1uUSeNPNG9OBNG8MM2sUSyEWAc0LT9izQ+b+7JCPuG7ut72gu2AZb4F9AvQKBgQCUWdiRV4QRAOnORlrCtuICk+qCDl9Xe5SsBgtokKQlMpsPWfJ58stxbbOxQecwYMP0EdP2bRIj7bE9k/Hksf23NbIGSYPhs19fsWaREuyuwodpVH2WwevLd0UOEPpYEvjJQkluSVKL6wAdxtCjD6dixpKz5OHBX6yOrKnSZrz0CwKBgQDTFk9hTRswjVECNjXKwjqwQbc8Zt3b/uKICQxhhllKrJ2fes4g86SUR6/0Cju4zQfJvgUb3pBOoQDvkLvRCtG6yDJk6Derl7Vtz4MAQjS+OFSZxCed/FSF2y5hyocKiD71lb+mxKFPWthLCIrz/op+I0uMinVwBLAwJfoLmdIBQQ==
  # \u5E94\u7528\u516C\u94A5
  publickey : MIIIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1h2BgyqNWweZMQ8iAt5Oxcs32RqCaCsUYaQP5zK5utXdf9hAKjSWCEZfRnGou2y+TLRwl6HJGCl9AFhqEoxJ5dLVWmY3ehkTY83FcpsOuuIel83HI8ROnOzjXlNIxZ4BGXkPbxq6sqNrc+cI6haHpEtsyIp4Ryl/9lCwRloQN0hF4skzSNysmJHKS9cpShMvDejviZ0O3KmEeTqSHAU54bhCJgccy9NgE9ZoMwja+aWloDOMfJA9K9yqLpQhFqfQG+QqQ2ZbYYBWBt1YzUgESpseQU/VHGQ/IF0qSFN6M3fT3opYL27YHjGol5E/cP+G07CgizglJDZh5fPQ+VFoXwIDAQAB

  # \u652F\u4ED8\u5B9D\u516C\u94A5
  aliPublicKey : MIIIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlV1enacaA5njsZrQmAmyUCD9GuYXLrZ9pCYrHeDJO9Kaa2AZKJUWwxnI9imVVXTqo2KWm3e0G7O1oPjFigvJWoxP3oQK/0v3zRskI/u9dqFqPsovsizuQSEcT2hrAAGDQWor9Df6gD0qgsJbQFqB7Pg4Aa6/52djjnbY6U7fseUbF0m4x2KatI/djpN0zFlZG+us2uH/yU2CfYdOEGleTesTJy/pZT5nYQPPQ7FEJ8LcjlBWn9h7XcIlmCrzOt5KmbUBmpqy4Rd+iDnzrrEW1nYUw3jcZTbEkETV4IEgaSol058amvU7tEeMFgjLCT5F2+qRY1qtoeZa3PvRpCMNGwIDAQAB

  #\u670D\u52A1\u5668\u5F02\u6B65\u901A\u77E5\u9875\u9762\u8DEF\u5F84
  notitfyurl : http://localhost:8085/cancel.html
  #\u9875\u9762\u8DF3\u8F6C\u540C\u6B65\u901A\u77E5\u9875\u9762\u8DEF\u5F84
  returnurl : http://localhost:8085/success.html

  #\u7B7E\u540D\u65B9\u5F0F
  signtype : RSA2
  #\u5B57\u7B26\u7F16\u7801\u683C\u5F0F
  charset : utf-8
  #\u652F\u4ED8\u5B9D\u7F51\u5173
  gatwayurl : https://openapi-sandbox.dl.alipaydev.com/gateway.do

